config:
  oidc:
    clientID: "kube"
    issuerURL: "https://keycloak.adiachan.cn/auth/realms/kind"
    scopes: "email,groups,offline_access"
    useAccessToken: false
  enableHelm: false

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto $scheme;
    nginx.ingress.kubernetes.io/server-snippet: |-
      large_client_header_buffers 4 64k;

  hosts:
    - host: headlamp.adiachan.cn
      paths:
      - path: /
        type: ImplementationSpecific
  tls:
   - secretName: headlamp-tls
     hosts:
       - headlamp.adiachan.cn
